### ISSUE TITLE
Is it possible to use actual java class files as native(library) classes?

### ISSUE THREAD

**Issue by shnjm** [szatkus/js2me#14]
Hello @szatkus ,
This is a awesome project and you did great. Thank you for that.

I am interested to know if it is possible to use actual class files for CLDC & MIDP runtime and replace the JavaScript object approach in the /js/me folder. So that, use pure java classes and implement minimal interface using the JavaScript object approach to communicate with browser(canvas, sound, events etc.). Using this approach maybe it is possible to reuse existing java codebase and no need to implement everything in JS.

My concerns are,
1. Is this approach possible?
2. Is this approach require more resources and make the VM very slow?
3. What are the possibilities and concerns?

Can you please provide some insights regarding this idea?

**Comment by szatkus** [comment]
One of the engines generates JS code from Java bytecode. It should be possible to built an AOT on top of that to generate stdlib from existing Java code if you have anything like this.

**Comment by shnjm** [comment]
That is interesting to me. Do you have any interest to implement and change current implementation for that?

You have provided so much efforts in the JavaScript object approach. I am not sure if it is okay to change the plan and redo everything now.

**Comment by szatkus** [comment]
Not really. The project is effectievely dead now.

**Comment by shnjm** [comment]
Okay, got your point. Maybe I can do some experiments before I lose interest.

Again, many thanks for your efforts and make them MIT licensed.

So I am closing the issue now. But always open to continue discussion(if any).
